name: Virgo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4953
title: Virgo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#25ea81'
    - '#20ce87'
    - '#c7cad3'
    - '#edeef2'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
