name: Virgo
favicon: null
layout_spectrum: 0.02104
typography_spectrum: 0.74386
title: Virgo
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#25ea81'
    - '#20ce87'
    - '#c7cad3'
    - '#edeef2'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
